[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
rayon = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
dashmap = "6.1.0"
anyhow = { workspace = true }
yara = { version = "0.27", features = ["vendored"] }
