[package]
name = "trustroot"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
rcgen = "0.11"
rsa = "0.9"
pkcs8 = { version = "0.10", features = ["std", "pem"] }
