/**
 * init_env — generates a .env for a single-node deployment.
 *
 * .env.example ships placeholder secrets ("aB1!aB1!…") that satisfy the schema's
 * complexity rules, so a node started from it boots happily with publicly known
 * credentials. This generates real ones from the CSPRNG instead, and never
 * overwrites an existing .env.
 */

const ENV_PATH = "./.env";

function secret(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  // base64url keeps it shell-safe; the suffix guarantees the schema's
  // upper/lower/digit-or-special complexity requirement is met.
  const body = btoa(String.fromCharCode(...bytes))
    .replace(/[+/=]/g, "")
    .slice(0, 40);
  return `${body}aA1!`;
}

function render(singleNode: boolean, production: boolean): string {
  // One bypass token, referenced twice: SystemLifecycleService.verifyHardware only
  // accepts the bypass when SECURE_ENVIRONMENT_TOKEN matches SECURE_BYPASS_TOKEN.
  const bypass = secret();

  return `# Counter-Terrorist — generated by \`deno task setup\`. Do not commit.
# Regenerate with: rm .env && deno task setup

# --- Security ---
API_TOKEN="${secret()}"
MESH_SECRET="${secret()}"
PKI_SECRET="${secret()}"
SECURE_BYPASS_TOKEN="${bypass}"
SECURE_ENVIRONMENT_TOKEN="${bypass}"

# --- Operational ---
ENVIRONMENT="${production ? "production" : "development"}"
PORT="8000"
SINGLE_NODE="${singleNode}"
LOG_LEVEL="INFO"
ALLOWED_ORIGINS="http://localhost:8000"
SESSION_TTL_HOURS="24"

# --- Hardware root of trust ---
# A host without a TPM (or without /dev/tpm* exposed) cannot satisfy PCR
# attestation. In development the bypass tokens above stand in for it; production
# requires a real TPM and rejects these two settings at boot.
STRICT_HARDWARE_INTEGRITY="${production}"
ALLOW_HARDWARE_BYPASS="${!production}"

# --- Governance ---
STRICT_POLICY_ENFORCEMENT="false"

# --- Intelligence ---
INTEL_SYNC_INTERVAL_HOURS="24"
INTEL_ALLOWLIST="127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
`;
}

if (import.meta.main) {
  const args = new Set(Deno.args);
  const force = args.has("--force");
  const production = args.has("--production");
  const singleNode = !args.has("--mesh");

  const exists = await Deno.stat(ENV_PATH).then(() => true).catch(() => false);
  if (exists && !force) {
    console.error(`Refusing to overwrite the existing ${ENV_PATH}. Pass --force to replace it.`);
    Deno.exit(1);
  }

  await Deno.writeTextFile(ENV_PATH, render(singleNode, production));
  await Deno.chmod(ENV_PATH, 0o600).catch(() => {});

  console.log(`Wrote ${ENV_PATH} (mode 600) with freshly generated secrets.`);
  console.log(`  ENVIRONMENT = ${production ? "production" : "development"}`);
  console.log(`  SINGLE_NODE = ${singleNode}`);
  if (production) {
    console.log("\nProduction profile: a working TPM 2.0 stack is required or the boot will abort.");
  }
  console.log("\nRetrieve the dashboard token with:  grep '^API_TOKEN' .env");
}
