[package]
name = "pcap"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
socket2 = { version = "0.5", features = ["all"] }
anyhow = "1.0"
