[package]
name = "netcap"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rmp-serde = "1.1"
tokio = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
chrono = { workspace = true }
socket2 = { version = "0.5", features = ["all"] }
anyhow = "1.0"
nix = { version = "0.27", features = ["net"] }
libc = "0.2"
shared_memory = "0.12"
bytes = "1.4"
