[package]
name = "sentinel-common"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { version = "0.1", optional = true }
aya-log-ebpf = { version = "0.1", optional = true }
aya = { version = "0.12", optional = true }

[features]
user = ["dep:aya"]
kernel = ["dep:aya-ebpf", "dep:aya-log-ebpf"]
