[package]
name = "enforcer"
version = "0.1.0"
edition = "2021"

[dependencies]
cts_ipc = { path = "../cts_ipc" }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
